---
resource_pools:
  - name: prometheus
    network: prometheus
    stemcell: (( grab meta.stemcell ))
    cloud_properties: {}

compilation:
  workers: 3
  network: prometheus
  cloud_properties: {}

jobs:
  - name: alertmanager
    resource_pool: prometheus

  - name: prometheus
    resource_pool: prometheus

  - name: db
    resource_pool: prometheus

  - name: grafana
    resource_pool: prometheus

  - name: nginx
    resource_pool: prometheus
