#!/bin/bash

set -e

echo "Generating credentials for Prometheus"
safe gen ${VAULT_PREFIX}/creds/alertmanager password -- \
     gen ${VAULT_PREFIX}/creds/db password -- \
     gen ${VAULT_PREFIX}/creds/grafana password -- \
     gen ${VAULT_PREFIX}/creds/grafana secret_key -- \
     gen ${VAULT_PREFIX}/creds/prometheus password > /dev/null
